name: lrann 
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - jupyterlab
  - pandas
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - lightfm
  - tqdm
  - statsmodels
  - requests

